common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'common'

urlpatterns = [
  path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
  path('logout/', auth_views.LogoutView.as_view(), name='logout'),
  path('signup/', views.signup, name='signup'),
]

common/models.py
from django.db import models

# Create your models here.

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
  email = forms.EmailField(label="이메일")

  class Meta:
    model = User
    fields = ("username", "password1", "password2", "email")

common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm


def signup(request):
  if request.method == "POST":
    form = UserForm(request.POST)
    if form.is_valid():
      form.save()
      # username = request.POST.get('username')
      # raw_password = request.POST.get('password1')
      username = form.cleaned_data.get('username')
      raw_password = form.cleaned_data.get('password1')
      user = authenticate(username=username, password=raw_password)  # 사용자 인증
      login(request, user)  # 로그인
      return redirect('index')
  else:
    form = UserForm()
  return render(request, 'common/signup.html', {'form': form})

templates/common/login.html
{% extends 'base.html' %}

{% block contents %}
<div class="container my-3">
  <form method="post" action="{% url 'common:login' %}">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}">  <!-- 로그인 성공후 이동되는 URL -->
    {% include 'form_errors.html' %}
    <div class="mb-3">
      <label for="username">사용자ID</label>
      <input type="text" class="form-control" name="username" id="username"
        value="{{ form.username.value|default_if_none:'' }}">
    </div>
    <div class="mb-3">
      <label for="password">비밀번호</label>
      <input type="password" class="form-control" name="password" id="password"
        value="{{ form.password.value|default_if_none:'' }}">
    </div>
    <button type="submit" class="btn btn-primary">로그인</button>
  </form>
</div>
{% endblock contents %}

templates/common/signup.html
{% extends "base.html" %}

{% block contents %}
<div class="container my-3">
  <form method="post" action="{% url 'common:signup' %}">
    {% csrf_token %}
    {% include "form_errors.html" %}
    <div class="mb-3">
        <label for="username">사용자 이름</label>
        <input type="text" class="form-control" name="username" id="username"
          value="{{ form.username.value|default_if_none:'' }}">
    </div>
    <div class="mb-3">
        <label for="password1">비밀번호</label>
        <input type="password" class="form-control" name="password1" id="password1"
          value="{{ form.password1.value|default_if_none:'' }}">
    </div>
    <div class="mb-3">
        <label for="password2">비밀번호 확인</label>
        <input type="password" class="form-control" name="password2" id="password2"
          value="{{ form.password2.value|default_if_none:'' }}">
    </div>
    <div class="mb-3">
        <label for="email">이메일</label>
        <input type="text" class="form-control" name="email" id="email"
          value="{{ form.email.value|default_if_none:'' }}">
    </div>
    <button type="submit" class="btn btn-primary">생성하기</button>
  </form>
</div>
{% endblock contents %}