common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'common'

urlpatterns = [
  path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
  path('logout/', auth_views.LogoutView.as_view(), name='logout'),
  path('signup/', views.signup, name='signup'),
]

py_board/urls.py
from django.urls import path, re_path

from . import views

app_name = 'py_board'

urlpatterns = [
  path('', views.index, name='index'),
  path('<int:question_id>/', views.detail, name='detail'),
  
  path('question/create/', views.question_create, name='question_create'),
  path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
  path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
  path('question/vote/<int:question_id>/', views.question_vote, name='question_vote'),
  
  path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
  path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
  path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),
  path('answer/vote/<int:answer_id>/', views.answer_vote, name='answer_vote'),
]

py_board/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Question(models.Model):
  author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question')
  subject = models.CharField(max_length=200)
  content = models.TextField()
  created_at = models.DateTimeField()
  updated_at = models.DateTimeField(null=True, blank=True)
  voter = models.ManyToManyField(User, related_name='voter_question') # 추천인
  
  def __str__(self):
    return self.subject

class Answer(models.Model):
  author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='author_answer')
  question = models.ForeignKey(Question, on_delete=models.CASCADE)
  content = models.TextField()
  created_at = models.DateTimeField()
  updated_at = models.DateTimeField(null=True, blank=True)
  voter = models.ManyToManyField(User, related_name='voter_answer') # 추천인

py_board/views/answer_views.py
from django.http import HttpResponseNotAllowed
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils import timezone

from ..models import Question, Answer
from ..forms import AnswerForm

# Create your views here.
# # 방법1
# def answer_create(req, question_id):
#   print(question_id)
#   question = get_object_or_404(Question, pk=question_id)
#   question.answer_set.create( # answer_set는 Answer model과 관계의 의미
#     content=req.POST.get('content'),
#     created_at=timezone.now()
#   )
#   return redirect('py_board:detail', question_id=question.id)

# # 방법2
# def answer_create(req, question_id):
#   question = get_object_or_404(Question, pk=question_id)
#   answer = Answer(
#     question=question,
#     content=req.POST.get('content'),
#     created_at=timezone.now()
#   )
#   answer.save()
#   return redirect('py_board:detail', question_id=question.id)

# 방법3
@login_required(login_url='common:login')
def answer_create(req, question_id):
  question = get_object_or_404(Question, pk=question_id)
  
  if req.method == 'POST':
    form = AnswerForm(req.POST)
    if form.is_valid():
      answer = form.save(commit=False)
      answer.author = req.user  # author 속성에 로그인 계정 저장
      answer.created_at = timezone.now()
      answer.question = question
      answer.save()
      return redirect('{}#answer_{}'.format(
        resolve_url('py_board:detail', question_id=question.id), answer.id
      ))
      # return redirect('py_board:detail', question_id=question.id)
  else:
    return HttpResponseNotAllowed('Only POST is possible.')

  context = {'question': question, 'form': form}
  return render(req, 'question_detail.html', context)

@login_required(login_url='common:login')
def answer_modify(req, answer_id):
  answer = get_object_or_404(Answer, pk=answer_id)
  if req.user != answer.author:
    messages.error(req, '수정권한이 없습니다')
    return redirect('py_board:detail', question_id=answer.question.id)
  if req.method == "POST":
    form = AnswerForm(req.POST, instance=answer)
    if form.is_valid():
      answer = form.save(commit=False)
      answer.updated_at = timezone.now()
      answer.save()
      return redirect('{}#answer_{}'.format(
        resolve_url('py_board:detail', question_id=answer.question.id), answer.id
      ))
  else:
    form = AnswerForm(instance=answer)

  context = {'answer': answer, 'form': form}
  return render(req, 'answer_form.html', context)

@login_required(login_url='common:login')
def answer_delete(req, answer_id):
  answer = get_object_or_404(Answer, pk=answer_id)
  if req.user != answer.author:
    messages.error(req, '삭제권한이 없습니다')
  else:
    answer.delete()

  return redirect('py_board:detail', question_id=answer.question.id)

@login_required(login_url='common:login')
def answer_vote(request, answer_id):
  answer = get_object_or_404(Answer, pk=answer_id)
  if request.user == answer.author:
    messages.error(request, '본인이 작성한 글은 추천할수 없습니다')
  else:
    answer.voter.add(request.user)
  return redirect('{}#answer_{}'.format(
    resolve_url('py_board:detail', question_id=answer.question.id), answer.id
  ))

py_board/views/base_views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from django.db.models import Q

from ..models import Question

# Create your views here.
def index(req):
  page = req.GET.get('page', '1')
  question_list = Question.objects.order_by('-created_at')
  paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
  page_obj = paginator.get_page(page)
  context = {'question_list': page_obj}
  return render(req, 'question_list.html', context)

# shell 이용하여 테스트 리스트 생성하가
"""
from pybo.models import Question
from django.utils import timezone
for i in range(300):
  q = Question(subject='테스트 데이터입니다:[%03d]' % i, content='내용무', created_at=timezone.now())
  q.save()
"""

def detail(req, question_id):
  question = get_object_or_404(Question, id=question_id) # Question.objects.get(id=question_id)
  context = {'question': question}
  return render(req, 'question_detail.html', context)

def index(req):
  page = req.GET.get('page', '1')  # 페이지
  kw = req.GET.get('kw', '')  # 검색어
  question_list = Question.objects.order_by('-created_at')
  if kw:
    question_list = question_list.filter(
      Q(subject__icontains=kw) |  # 제목 검색
      Q(content__icontains=kw) |  # 내용 검색
      Q(answer__content__icontains=kw) |  # 답변 내용 검색
      Q(author__username__icontains=kw) |  # 질문 글쓴이 검색
      Q(answer__author__username__icontains=kw)  # 답변 글쓴이 검색
    ).distinct()
  paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
  page_obj = paginator.get_page(page)

  context = {'question_list': page_obj, 'page': page, 'kw': kw}
  return render(req, 'question_list.html', context)

py_board/views/question_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils import timezone

from ..models import Question
from ..forms import QuestionForm

# Create your views here.
@login_required(login_url='common:login')
def question_create(req):
  if req.method == 'POST':
    form = QuestionForm(req.POST)
    if form.is_valid():
      question = form.save(commit=False)
      question.author = req.user
      question.created_at = timezone.now()
      question.save()
      return redirect('py_board:index')
  else:
    form = QuestionForm()

  context = {'form': form}
  return render(req, 'question_form.html', context)

@login_required(login_url='common:login')
def question_modify(req, question_id):
  question = get_object_or_404(Question, pk=question_id)
  if req.user != question.author:
    messages.error(req, '수정권한이 없습니다')
    return redirect('py_board:detail', question_id=question.id)
  if req.method == "POST":
    form = QuestionForm(req.POST, instance=question)
    if form.is_valid():
      question = form.save(commit=False)
      question.updated_at = timezone.now()  # 수정일시 저장
      question.save()
      return redirect('py_board:detail', question_id=question.id)
  else:
    form = QuestionForm(instance=question)

  context = {'form': form}
  return render(req, 'question_form.html', context)

@login_required(login_url='common:login')
def question_delete(req, question_id):
  question = get_object_or_404(Question, pk=question_id)
  if req.user != question.author:
    messages.error(req, '삭제권한이 없습니다')
    return redirect('py_board:detail', question_id=question.id)
  question.delete()
  return redirect('py_board:index')

@login_required(login_url='common:login')
def question_vote(req, question_id):
  question = get_object_or_404(Question, pk=question_id)
  if req.user == question.author:
    messages.error(req, '본인이 작성한 글은 추천할수 없습니다')
  else:
    question.voter.add(req.user)

  return redirect('py_board:detail', question_id=question.id)
  

templates/answer_form.html
{% extends 'base.html' %}
{% block contents %}
<!-- 답변 수정-->
<div class="container my-3">
  <form method="POST">
    {% csrf_token %}
    {% include "form_errors.html" %}
    <div class="mb-3">
      <label for="content" class="form-label">답변내용</label>
      <textarea class="form-control" name="content" id="content"
        rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
    </div>
    <button type="submit" class="btn btn-primary">저장하기</button>
  </form>
</div>
{% endblock contents %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Py Board</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>
<body>
  {% include "navbar.html" %}
  {% block contents %}
  {% endblock contents %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
  {% block scripts %}{% endblock scripts %}
</body>
</html>

templates/form_errors.html
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'py_board:index' %}">Py Board</a>
    <button class="navbar-toggler" type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
          {% else %}
            <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
          {% endif %}
        </li>
        <li>
          {% if not user.is_authenticated %}
          <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
          {% endif %}
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/question_detail.html
{% extends 'base.html' %}
{% load py_board_filter %}
{% block contents %}
<div class="container my-3">
  {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
      {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul>
          <li>{{ message.message }}</li>
        </ul>
      {% endfor %}
    </div>
  {% endif %}
  <h2 class="border-bottom py-2">{{ question.subject }}</h2>
  <div class="card my-3">
    <div class="card-body">
      <div class="card-text" style="white-space: pre-line;">{{ question.content|mark }}</div>
      <div class="d-flex justify-content-end">
        {% if question.updated_at %}
          <div class="badge bg-light text-dark p-2 text-start mx-3">
            <div class="mb-2">updated_at</div>
            <div>{{ question.updated_at }}</div>
          </div>
        {% endif %}
        
        <div class="badge bg-light text-dark p-2 text-start">
          <div class="mb-2">{{ question.author.username }}</div>
          <div>{{ question.created_at }}</div>
        </div>
      </div>
      <div class="my-3">
        <a href="javascript:void(0)" data-uri="{% url 'py_board:question_vote' question.id  %}"
          class="recommend btn btn-sm btn-outline-secondary"> 추천
          <span class="badge rounded-pill bg-success">{{question.voter.count}}</span>
        </a>
        {% if request.user == question.author %}
          <a href="{% url 'py_board:question_modify' question.id  %}" 
            class="btn btn-sm btn-outline-secondary">수정</a>
          <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
            data-uri="{% url 'py_board:question_delete' question.id  %}">삭제</a>
        {% endif %}
      </div>
    </div>
  </div>
  <!-- 답변 -->
  <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
  {% for answer in question.answer_set.all %}
    <a id="answer_{{ answer.id }}"></a>
  {% endfor %}
  {% for answer in question.answer_set.all %}
  <div class="card my-3">
    <div class="card-body">
      <div class="card-text" style="white-space: pre-line;">{{ answer.content|mark }}</div>
      <div class="d-flex justify-content-end">
        {% if answer.updated_at %}
          <div class="badge bg-light text-dark p-2 text-start mx-3">
            <div class="mb-2">updated_at</div>
            <div>{{ answer.updated_at }}</div>
          </div>
        {% endif %}
        <div class="badge bg-light text-dark p-2 text-start">
          <div class="mb-2">{{ answer.author.username }}</div>
          <div>{{ answer.created_at }}</div>
        </div>
        <div class="my-3">
          <a href="javascript:void(0)" data-uri="{% url 'py_board:answer_vote' answer.id  %}"
            class="recommend btn btn-sm btn-outline-secondary"> 추천
            <span class="badge rounded-pill bg-success">{{answer.voter.count}}</span>
          </a>
          {% if request.user == answer.author %}
            <a href="{% url 'py_board:answer_modify' answer.id  %}" 
              class="btn btn-sm btn-outline-secondary">수정</a>
            <a href="#" class="delete btn btn-sm btn-outline-secondary "
              data-uri="{% url 'py_board:answer_delete' answer.id  %}">삭제</a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
  <!-- 답변 등록 -->
  <form action="{% url 'py_board:answer_create' question.id %}" method="POST" class="my-3">
    {% csrf_token %}
    <div class="mb-3">
      <label for="content" class="form-label">답변내용</label>
      <textarea {% if not user.is_authenticated %}disabled{% endif %} 
        name="content" id="content" class="form-control" rows="10"></textarea>
    </div>
    <input type="submit" value="답변등록" class="btn btn-primary">
  </form>
</div>
{% endblock contents %}

{% block scripts %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
  element.addEventListener('click', function() {
    if(confirm("정말로 삭제하시겠습니까?")) {
      location.href = this.dataset.uri;
    };
  });
});
const recommend_elements = document.getElementsByClassName("recommend");
Array.from(recommend_elements).forEach(function(element) {
  element.addEventListener('click', function() {
    if(confirm("정말로 추천하시겠습니까?")) {
      location.href = this.dataset.uri;
    };
  });
});
</script>
{% endblock scripts %}

templates/question_form.html
{% extends 'base.html' %}

{% block contents %}
<div class="container">
  <h5 class="my-3 border-bottom pb-2">질문등록</h5>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">저장하기</button>
  </form>
</div>
{% endblock contents %}

templates/question_list.html
{% extends 'base.html' %}
{% load py_board_filter %}
{% block contents %}
<div class="container my-3">
  <div class="row my-3">
    <div class="col-6">
      <a href="{% url 'py_board:question_create' %}" class="btn btn-primary">질문 등록하기</a>
    </div>
    <div class="col-6">
      <div class="input-group">
        <input type="text" id="search_kw" class="form-control" value="{{ kw|default_if_none:'' }}">
        <div class="input-group-append">
          <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
        </div>
      </div>
    </div>
  </div>
  <table class="table">
    <thead>
      <tr class="text-center table-dark">
        <th>번호</th>
        <th style="width:50%">제목</th>
        <th>글쓴이</th>
        <th>작성일시</th>
      </tr>
    </thead>
    <tbody>
    {% if question_list %}
      {% for question in question_list %}
        <tr class="text-center">
          <td>
            <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
            {{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}
          </td>
          {% comment %} <td>{{ forloop.counter }}</td> {% endcomment %}
          <td class="text-start">
            <a href="{% url 'py_board:detail' question.id %}">{{ question.subject }}</a>
            {% if question.answer_set.count > 0 %}
              <span class="text-danger small mx-2">{{ question.answer_set.count }}</span>
            {% endif %}
          </td>
          <td>{{ question.author.username }}</td>
          <td>{{ question.created_at }}</td>
        </tr>
      {% endfor %}
    {% else %}
      <tr>
        <td colspan="4">질문이 없습니다.</td>
      </tr>
    {% endif %}
    </tbody>
  </table>
  <ul class="pagination justify-content-center">
    <!-- 이전페이지 -->
    {% if question_list.has_previous %}
      <li class="page-item">
        {% comment %} <a class="page-link" href="?page={{ question_list.previous_page_number }}">이전</a> {% endcomment %}
        <a class="page-link" data-page="{{ question_list.previous_page_number }}"
          href="javascript:void(0)">이전</a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
      </li>
    {% endif %}
    <!-- 페이지리스트 -->
    {% for page_number in question_list.paginator.page_range %}
      {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
        {% if page_number == question_list.number %}
          <li class="page-item active" aria-current="page">
            {% comment %} <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a> {% endcomment %}
            <a class="page-link" data-page="{{ page_number }}"
              href="javascript:void(0)">{{ page_number }}</a>
          </li>
        {% else %}
          <li class="page-item">
            {% comment %} <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a> {% endcomment %}
            <a class="page-link" data-page="{{ page_number }}"
              href="javascript:void(0)">{{ page_number }}</a>
          </li>
        {% endif %}
      {% endif %}
    {% endfor %}
    <!-- 다음페이지 -->
    {% if question_list.has_next %}
      <li class="page-item">
        {% comment %} <a class="page-link" href="?page={{ question_list.next_page_number }}">다음</a> {% endcomment %}
        <a class="page-link" data-page="{{ question_list.next_page_number }}"
          href="javascript:void(0)">다음</a>
      </li>
    {% else %}
      <li class="page-item disabled">
          <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
      </li>
    {% endif %}
  </ul>
  <a href="{% url 'py_board:question_create' %}" class="btn btn-primary">질문 등록하기</a>
</div>
<form id="searchForm" method="get" action="{% url 'index' %}">
  <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
  <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
{% endblock contents %}

{% block scripts %}
<script>
const page_elements = document.getElementsByClassName("page-link");
Array.from(page_elements).forEach(function(element) {
  element.addEventListener('click', function() {
    document.getElementById('page').value = this.dataset.page;
    document.getElementById('searchForm').submit();
  });
});
const btn_search = document.getElementById("btn_search");
btn_search.addEventListener('click', function() {
  console.log("ddd");
  document.getElementById('kw').value = document.getElementById('search_kw').value;
  document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
  document.getElementById('searchForm').submit();
});
</script>
{% endblock scripts %}